### ISSUE TITLE
No module named 'http_server' on latest docker container.

### ISSUE THREAD

**Issue by pax0707** [dgtlmoon/sockpuppetbrowser#7]
```
Traceback (most recent call last):
  File "/usr/src/app/./server.py", line 7, in <module>
    from http_server import start_http_server
ModuleNotFoundError: No module named 'http_server'
Traceback (most recent call last):
  File "/usr/src/app/./server.py", line 7, in <module>
    from http_server import start_http_server
ModuleNotFoundError: No module named 'http_server'
Traceback (most recent call last):
  File "/usr/src/app/./server.py", line 7, in <module>
    from http_server import start_http_server
ModuleNotFoundError: No module named 'http_server'
Traceback (most recent call last):
  File "/usr/src/app/./server.py", line 7, in <module>
```

**Comment by pax0707** [comment]
Fixed in newer release.
